services:
  auth-db:
    image: postgres:18-alpine
    ports:
      - 1001:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - ./db-data:/var/lib/postgres/data
